version: '3'
services:
    maven:
        container_name: maven-container
        build:
            context: .
            dockerfile: dockerfile_maven

    tomcat:
        container_name: tomcat-container
        build:
            context: .
            dockerfile: dockerfile_tomcat
        ports:
           - "8080:8080"
        volumes:
           - /tmp/war-web-project/target/wwp-1.0.0.war:/usr/local/tomcat/webapps/