---
version: '3'
services:
    maven:
        image: maven:3.5.2-jdk-8
        container_name: maven-container
        build:
            context: .
        volumes:
           - /tmp/war-web-project/target/wwp-1.0.0.war:/usr/local/tomcat/webapps/
    tomcat:
        image: maven:3.5.2-jdk-8
        container_name: tomcat-container
        build:
            context: .
        ports:
           - "80:8080"
        volumes:
           - /tmp/war-web-project/target/wwp-1.0.0.war:/usr/local/tomcat/webapps/
